Repository 1995-s-Project/1995-s_GroupWare, pull requests merged in 2024-12, with the labels that each got.

#105 <241210>구조동물(등록,삭제)
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/AnimalDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/AnimalsDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/BreedDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/EmpDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/PageDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/TypeAndBreedAndEmpAndAnimalDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/TypeDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/animalimages/581f2d77-d381-4547-99bf-226b93ff9797-dog.jpg
  semi-project/src/main/resources/static/animalimages/587ee285-71d8-4384-868c-f7022e2e708e-dogdog.PNG
  semi-project/src/main/resources/static/animalimages/5c3dbd64-ba77-4c83-a1a8-0f6c35e0e72f-dog.jpg
  semi-project/src/main/resources/static/animalimages/6e30e66a-b8d4-4cb7-a0ff-c5131926f060-cat.jpg
  semi-project/src/main/resources/static/animalimages/7d457755-42e6-4260-ae12-f72b48c1d4a5-dog.jpg
  semi-project/src/main/resources/static/animalimages/9f72440a-072f-43c5-9d0f-2ec88c86e047-dogdog.PNG
  semi-project/src/main/resources/static/animalimages/a5be7d6e-e9b0-48fc-b799-a01f7c01a149-dog.jpg
  semi-project/src/main/resources/static/animalimages/bdb52955-94b1-41d5-8629-91471d34d87e-dog.jpg
  semi-project/src/main/resources/static/animalimages/cat.jpg
  semi-project/src/main/resources/static/animalimages/defaultAnimal.jpg
  semi-project/src/main/resources/static/animalimages/dog.jpg
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-insert-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#108 [24.12.10] 메인 페이지 대시보드 구현
  semi-project/src/main/resources/static/img/adapt_icon/1.png
  semi-project/src/main/resources/static/img/adapt_icon/2.png
  semi-project/src/main/resources/static/img/adapt_icon/3.png
  semi-project/src/main/resources/static/main/css/mainPage.css
  semi-project/src/main/resources/static/main/js/main.js
  semi-project/src/main/resources/templates/main/main.html
Labels: 🖥️프론트엔드🖥️, ✅PR(Pull Request)✅

#110 [24.12.11] 로그인 정보 불러오기 구현(임시)
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/MainController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/UserInfoController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/dto/UserInfoResponse.java
  semi-project/src/main/resources/static/main/css/mainPage.css
  semi-project/src/main/resources/static/main/css/user-info.css
  semi-project/src/main/resources/static/main/js/user-info.js
  semi-project/src/main/resources/templates/main/main.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#111 전사게시판/수정/url변경
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTO.java
  semi-project/src/main/resources/mappers/employeeMapper.xml
  semi-project/src/main/resources/static/sidemenu/board/css/board-style.css
  semi-project/src/main/resources/static/sidemenu/board/css/regist.css
  semi-project/src/main/resources/static/sidemenu/board/css/search.css
  semi-project/src/main/resources/static/sidemenu/board/css/title.css
  semi-project/src/main/resources/static/sidemenu/board/css/update.css
  semi-project/src/main/resources/templates/sidemenu/board/board.html
  semi-project/src/main/resources/templates/sidemenu/board/regist.html
  semi-project/src/main/resources/templates/sidemenu/board/search.html
  semi-project/src/main/resources/templates/sidemenu/board/title.html
  semi-project/src/main/resources/templates/sidemenu/board/update.html
Labels: 🔙백엔드🔙

#112 <241211>구조동물 입양페이지
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/animalimages/89739939-c4bd-4d0a-8008-3c642985d1c9-dog.jpg
  semi-project/src/main/resources/static/animalimages/b9d236b7-56db-41e5-ae57-4c34f8fe73a9-dog.jpg
  semi-project/src/main/resources/static/animalimages/e3496e97-6164-4c56-a049-00a3bfd7d9a1-dog.jpg
  semi-project/src/main/resources/static/animalimages/e67fc0d3-a2b1-4c3d-9162-b640a440c236-dog.jpg
  semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/adoptionComplete.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/errorPage.html
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#119 [24.12.12] 메인페이지 상단바(전사 게시판데이터 연결)
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
  semi-project/src/main/resources/static/img/arrow/left-arrow.png
  semi-project/src/main/resources/static/img/arrow/right-arrow.png
  semi-project/src/main/resources/static/main/css/mainPage.css
  semi-project/src/main/resources/static/main/css/slide-bar.css
  semi-project/src/main/resources/static/main/js/slide-bar.js
  semi-project/src/main/resources/templates/main/main.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#125 [24.12.12] 코드일부수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
  semi-project/src/main/resources/mappers/employeeMapper.xml
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#131 [24.12.12] 캘린더 추가, 근태DB연결
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/ScheduleDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
  semi-project/src/main/resources/mappers/scheduleMapper.xml
  semi-project/src/main/resources/static/main/css/main-style.css
  semi-project/src/main/resources/static/main/css/slide-bar.css
  semi-project/src/main/resources/static/main/js/user-info.js
  semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
  semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
  semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#133 <24.12.15 직원댓글>
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/DeptDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTOJOB.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/JobDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/deptDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/jobDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/img/profile/9IRO8BZA3xCWUbISuwRDECsVQb-1rKEFHOPHVxT7P67BEzXCXH7W0_jGAZ-r-nNFAFlNVXmrLWWqOzksYc0oWA.jpg
  semi-project/src/main/resources/static/sidemenu/employee/css/empdetail.css
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
  semi-project/src/main/resources/templates/sidemenu/employee/employee.html
  semi-project/src/main/resources/templates/sidemenu/employee/empregist.html
Labels: 🔙백엔드🔙

#134 [24.12.13]구조동물조회기능추가
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-insert-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/adoptionComplete.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#135 [24.12.13] 근태관리(출퇴근 시간, 휴가 갯수, DB연결 타이머 연결)
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckInResponseDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/CheckOutResponseDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/VacationDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
  semi-project/src/main/resources/mappers/scheduleMapper.xml
  semi-project/src/main/resources/static/main/js/user-info.js
  semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
  semi-project/src/main/resources/static/sidemenu/schedule/js/checkInOut.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/user-info.js
  semi-project/src/main/resources/templates/main/main.html
  semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
Labels: ✅PR(Pull Request)✅

#143 [24.12.15] 근태수정UI 및 DB 연결(중간Merge)
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeJoinListDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/AttendanceAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/AttendanceRequest.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dto/ScheduleDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/mappers/scheduleMapper.xml
  semi-project/src/main/resources/static/sidemenu/schedule/css/attendance.css
  semi-project/src/main/resources/static/sidemenu/schedule/js/attedance.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/getAttendance.js
  semi-project/src/main/resources/templates/sidemenu/schedule/attendance-request.html
  semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#145 [24.12.15] 근태수정 기능 추가
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/DateUtil.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/AttendanceAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
  semi-project/src/main/resources/mappers/scheduleMapper.xml
  semi-project/src/main/resources/static/sidemenu/schedule/css/attendance.css
  semi-project/src/main/resources/static/sidemenu/schedule/js/selectAttendanceRequest.js
  semi-project/src/main/resources/templates/sidemenu/schedule/attendance-request.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#153 [24.12.15] 코드 일부 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#154 [24.12.15]재고관리조회
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/InventoryDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/adoptionDetailAnimal-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/adoptionComplete.html
  semi-project/src/main/resources/templates/sidemenu/animals/adoptionDetailAnimal.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/stock.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#156 [24.12.16] 캘린더 js Date 날짜 포맷팅 수정
  semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#162 24.12.16댓글완료
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/resources/static/sidemenu/employee/css/empdetail.css
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#163 <24.12.16 시설물>
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/employee/css/empdetail.css
  semi-project/src/main/resources/static/sidemenu/facilities/css/facilities-style.css
  semi-project/src/main/resources/templates/sidemenu/employee/delete.html
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
  semi-project/src/main/resources/templates/sidemenu/facilities/facilities.html
Labels: 🖥️프론트엔드🖥️, ✅PR(Pull Request)✅

#164 [24.12.16] 관리자 결재함 UI, DB 연결
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerApprovalMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/ApprovalResponse.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/CacPaymentDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/OverTimeDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/RetirementDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/VacPaymentDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerApprovalService.java
  semi-project/src/main/resources/mappers/managerApproval.xml
  semi-project/src/main/resources/static/img/icon/document.png
  semi-project/src/main/resources/static/img/icon/left-arrow.png
  semi-project/src/main/resources/static/img/icon/right-arrow.png
  semi-project/src/main/resources/static/sidemenu/manager/css/approvalBox-style.css
  semi-project/src/main/resources/static/sidemenu/manager/js/approval-list.js
  semi-project/src/main/resources/templates/sidemenu/manager/approvalBox.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#165 [24.12.16]재고조회 및 구조동물 카테고리 CSS, 비동기처리
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/AnimalDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/InventoryDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/stock-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
  semi-project/src/main/resources/templates/sidemenu/animals/stock.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#169 [24.12.16]재고수량 수정 완료 알림창
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/static/sidemenu/animals/css/adoptionComplete-style.css
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/stock.html
Labels: 🔙백엔드🔙

#174 [24.12.17] 관리자 결재함 임시구현
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/ApprovalUserDTO.java
  semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
  semi-project/src/main/resources/static/sidemenu/approval/js/vacation-form.js
  semi-project/src/main/resources/templates/sidemenu/approval/vacation-form.html
  semi-project/src/main/resources/templates/sidemenu/manager/employeeRegister.html
  semi-project/src/main/resources/templates/user/signup.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#173 [24.12.17]구조동물 css 대폭 수정!!
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
Labels: 🖥️프론트엔드🖥️

#177 [24.12.17]구조동물 등록, 삭제 버튼 CSS
  semi-project/src/main/resources/static/sidemenu/animals/css/animals-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
Labels: 🖥️프론트엔드🖥️

#184 <24.12.18쪽지전체조회>
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/EmployeeDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/resources/mappers/emailMapper.xml
  semi-project/src/main/resources/static/sidemenu/board/css/board-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
Labels: 🔙백엔드🔙

#185 [24.12.18]입양진행중,입양완료,입양취소 조회
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dto/AdoptionDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
  semi-project/src/main/resources/mappers/animalAdopterMapper.xml
  semi-project/src/main/resources/static/sidemenu/adoption/css/adoption-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#190 [24.12.19] 연차 휴가 로직 구현
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerApprovalMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerApprovalService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleApiController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/dao/ScheduleMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/model/service/ScheduleService.java
  semi-project/src/main/resources/mappers/managerApproval.xml
  semi-project/src/main/resources/mappers/scheduleMapper.xml
  semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
  semi-project/src/main/resources/static/sidemenu/manager/js/approval-list.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/calendar.js
  semi-project/src/main/resources/templates/sidemenu/approval/readVacRequest.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#199 [24.12.21] 사용자 결재 로직 및 UI 구현 완료
  semi-project/src/main/java/com/ohgiraffers/semiproject/approval/controller/ApprovalController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/approval/model/dao/ApprovalMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/approval/model/service/ApprovalService.java
  semi-project/src/main/resources/mappers/approvalFrom.xml
  semi-project/src/main/resources/static/sidemenu/approval/css/approval-style.css
  semi-project/src/main/resources/static/sidemenu/approval/css/vacation-form.css
  semi-project/src/main/resources/static/sidemenu/approval/js/my-approval-list.js
  semi-project/src/main/resources/static/sidemenu/schedule/css/schedule-style.css
  semi-project/src/main/resources/templates/sidemenu/approval/approval.html
  semi-project/src/main/resources/templates/sidemenu/approval/createCac-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createOverTime-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createRetirement-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createVacation-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/myCacRequest.html
  semi-project/src/main/resources/templates/sidemenu/approval/myOverTimeRequest.html
  semi-project/src/main/resources/templates/sidemenu/approval/myRetireMentRequest.html
  semi-project/src/main/resources/templates/sidemenu/approval/myVacRequest.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#202 [24.12.22]댓글내역 상세페이지로 이동
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/CommentDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeDTOJOB.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/mypage/css/myComments-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/myMails-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/myPosts-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/mypage-style.css
  semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myMails.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
Labels: 🔙백엔드🔙

#209 [24.12.23]마이페이지(게시글내역,댓글내역)
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/AnimalDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/HealthCheckDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dto/InoculationDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/mypage/css/myComments-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/myMails-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/myPosts-style.css
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myMails.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#208 <24.12.23메일이동>
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/resources/mappers/emailMapper.xml
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/templates/sidemenu/mail/archived.html
  semi-project/src/main/resources/templates/sidemenu/mail/important.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
  semi-project/src/main/resources/templates/sidemenu/mail/trash.html
Labels: 🔙백엔드🔙

#216 <24.12.24이메일이동완료>
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/AttendanceAPIController.java
  semi-project/src/main/resources/mappers/emailMapper.xml
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/employee/css/employee-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
  semi-project/src/main/resources/templates/sidemenu/mail/archived.html
  semi-project/src/main/resources/templates/sidemenu/mail/important.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
  semi-project/src/main/resources/templates/sidemenu/mail/trash.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#217 정근희/직원관리(연차휴가추가생성)
  semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerVacationAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerVacationController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerVacationMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/VacationListDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/VacationManagementDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerVacationService.java
  semi-project/src/main/resources/mappers/managerVacationMapper.xml
  semi-project/src/main/resources/static/sidemenu/manager/css/scheduleManagement.css
  semi-project/src/main/resources/static/sidemenu/manager/css/vacationManagement.css
  semi-project/src/main/resources/static/sidemenu/manager/js/scheduleManagement.js
  semi-project/src/main/resources/static/sidemenu/manager/js/vacationManagement.js
  semi-project/src/main/resources/templates/sidemenu/manager/scheduleManagement.html
  semi-project/src/main/resources/templates/sidemenu/manager/vacationManagement.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#222 [24.12.25]마이페이지 회원정보수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/mypage/css/myComments-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/myPosts-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/mypage-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/settingInfo-style.css
  semi-project/src/main/resources/static/sidemenu/mypage/css/settingPass-style.css
  semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
  semi-project/src/main/resources/templates/sidemenu/mypage/settingInfo.html
  semi-project/src/main/resources/templates/sidemenu/mypage/settingPass.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#227 [24.12.26]마이페이지 회원정보수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/model/service/MyPageService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/img/profile/default.jpg
  semi-project/src/main/resources/static/sidemenu/mypage/css/mypage-style.css
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#228 <24.12.26 메일,메신저>
  semi-project/build.gradle
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/WebSocketConfig.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/MailDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dto/PageDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/MessengerController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dao/ChatMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dao/MessengerMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/ChatDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/MessengerDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/service/ChatService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/service/MessengerService.java
  semi-project/src/main/resources/mappers/chatMapper.xml
  semi-project/src/main/resources/mappers/emailMapper.xml
  semi-project/src/main/resources/mappers/employeeMapper.xml
  semi-project/src/main/resources/mappers/messengerMapper.xml
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
  semi-project/src/main/resources/static/sidemenu/messenger/css/messenger.css
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
  semi-project/src/main/resources/templates/sidemenu/mail/archived.html
  semi-project/src/main/resources/templates/sidemenu/mail/important.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
  semi-project/src/main/resources/templates/sidemenu/mail/trash.html
  semi-project/src/main/resources/templates/sidemenu/messenger/messenger.html
Labels: 🔙백엔드🔙

#229 정근희/관리자페이지구현
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dto/EmployeeScheduleInfoDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dao/ManagerDataMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/dto/ManagerDataListDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/model/service/ManagerService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/todo/controller/ToDoController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/todo/model/dao/ToDoMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/todo/model/dto/ToDoDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/todo/model/service/TodoService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/mappers/employeeMapper.xml
  semi-project/src/main/resources/mappers/managerMapper.xml
  semi-project/src/main/resources/mappers/todo.xml
  semi-project/src/main/resources/static/sidemenu/manager/css/manager-style.css
  semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
  semi-project/src/main/resources/templates/sidemenu/manager/manager.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#230 [24.12.26] 결재 카운트 코드 수정
  semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#231 [24.12.27] To-Do 리스트 로직 수정
  semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#233 [24.12.27] 채팅기능 구현중
  semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/controller/UserInfoController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/MessengerController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/ChatDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/MessengerDTO.java
  semi-project/src/main/resources/mappers/chatMapper.xml
  semi-project/src/main/resources/mappers/messengerMapper.xml
  semi-project/src/main/resources/static/main/js/user-info.js
  semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/user-info.js
  semi-project/src/main/resources/templates/main/main.html
  semi-project/src/main/resources/templates/sidemenu/messenger/messenger.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#234 <24.12.27 이메일css>
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/dao/MailMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/resources/mappers/emailMapper.xml
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/templates/sidemenu/mail/archived.html
  semi-project/src/main/resources/templates/sidemenu/mail/important.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
  semi-project/src/main/resources/templates/sidemenu/mail/trash.html
Labels: 🔙백엔드🔙

#236 (24.12.27) - 채팅 엔터누를시 전송 기능 추가 / css 수정
  semi-project/src/main/resources/static/img/profile/KakaoTalk_20241227_144243832.jpg
  semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
  semi-project/src/main/resources/templates/sidemenu/messenger/messenger.html
Labels: 🔙백엔드🔙

#239 <24.12.27 이메일전체선택수정>
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
Labels: 🔙백엔드🔙

#238 [24.12.27]입양페이지 - 등록기능구현
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/dao/AnimalsMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/model/service/AnimalsService.java
  semi-project/src/main/resources/mappers/animalAdopterMapper.xml
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/adoption/css/adoption-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoption.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#243 [24.12.29] 결재로직수정,사원등록 주소API 연동, 자동 사번부여, 권한체크 후 관리자 버튼 숨기거나 보이기
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/CustomAccessDeniedHandler.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/SecurityConfig.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/home/controller/UserController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/dto/UserInfoResponse.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/main/model/service/UserInfoService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/mappers/managerMapper.xml
  semi-project/src/main/resources/static/main/css/main-style.css
  semi-project/src/main/resources/static/main/js/main.js
  semi-project/src/main/resources/static/sidemenu/manager/css/employeeRegister-style.css
  semi-project/src/main/resources/static/sidemenu/manager/js/employeeRegister.js
  semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
  semi-project/src/main/resources/templates/sidemenu/manager/employeeRegister.html
  semi-project/src/main/resources/templates/sidemenu/manager/manager.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#245 <24.12.30발표전정리>
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/dao/BoardMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/model/service/BoardService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/mappers/employeeMapper.xml
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/templates/sidemenu/board/board.html
  semi-project/src/main/resources/templates/sidemenu/board/regist.html
  semi-project/src/main/resources/templates/sidemenu/board/search.html
  semi-project/src/main/resources/templates/sidemenu/board/title.html
  semi-project/src/main/resources/templates/sidemenu/board/update.html
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
  semi-project/src/main/resources/templates/sidemenu/employee/employee.html
  semi-project/src/main/resources/templates/sidemenu/employee/search.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
Labels: 🛠️수정🛠️

#246 [24.12.30]입양, 구조동물, 마이페이지 예외처리
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/controller/MyPageController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mypage/model/service/MyPageService.java
  semi-project/src/main/resources/mappers/animalMapper.xml
  semi-project/src/main/resources/static/sidemenu/animals/css/animalDetail-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/detailAnimal.html
  semi-project/src/main/resources/templates/sidemenu/animals/insert.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myComments.html
  semi-project/src/main/resources/templates/sidemenu/mypage/myPosts.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
  semi-project/src/main/resources/templates/sidemenu/mypage/settingPass.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙

#247 [24.12.30] 코드일부수정
  semi-project/src/main/resources/static/sidemenu/board/js/board.js
  semi-project/src/main/resources/static/sidemenu/manager/js/manager.js
  semi-project/src/main/resources/templates/sidemenu/board/board.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#248 [24.12.30] 슬라이드바 코드 일부수정
  semi-project/src/main/resources/static/main/js/slide-bar.js
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#249 [24.12.30] 발표 후 수정 필요
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoptCanceledDetail.html
  semi-project/src/main/resources/templates/sidemenu/adoption/adoptCompletedDetail.html
  semi-project/src/main/resources/templates/sidemenu/board/title.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#251 [24.12.30] 예외처리 및 메인페이지 DB연결
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/controller/AdoptionAPIController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/dao/AdoptionMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/approval/controller/ApprovalController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/GlobalExceptionHandler.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerAttendanceAPIController.java
  semi-project/src/main/resources/mappers/animalAdopterMapper.xml
  semi-project/src/main/resources/static/error/css/error.css
  semi-project/src/main/resources/static/main/js/count.js
  semi-project/src/main/resources/static/main/js/main.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/attedance.js
  semi-project/src/main/resources/static/sidemenu/schedule/js/form-validation.js
  semi-project/src/main/resources/templates/error.html
  semi-project/src/main/resources/templates/main/main.html
  semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/approval/cac-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createCac-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createOverTime-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createRetirement-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/createVacation-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/overTime-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/retirement-form.html
  semi-project/src/main/resources/templates/sidemenu/approval/vacation-form.html
  semi-project/src/main/resources/templates/sidemenu/manager/approvalBox.html
  semi-project/src/main/resources/templates/sidemenu/manager/manager.html
  semi-project/src/main/resources/templates/sidemenu/schedule/attendance-request.html
  semi-project/src/main/resources/templates/sidemenu/schedule/schedule.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#253 [24.12.30]마이페이지-게시글에러 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/adoption/model/service/AdoptionService.java
Labels: 🛠️수정🛠️

#254 [24.12.30] 관리자페이지 날짜 포맷팅 코드 수정
  semi-project/src/main/resources/templates/sidemenu/manager/manager.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#255 <24.12.30직원정보 css>
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/board/css/regist.css
  semi-project/src/main/resources/static/sidemenu/employee/css/dog.css
  semi-project/src/main/resources/static/sidemenu/employee/css/employee-style.css
  semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/templates/sidemenu/board/regist.html
  semi-project/src/main/resources/templates/sidemenu/board/title.html
  semi-project/src/main/resources/templates/sidemenu/board/update.html
  semi-project/src/main/resources/templates/sidemenu/employee/customer.html
  semi-project/src/main/resources/templates/sidemenu/employee/dog.html
  semi-project/src/main/resources/templates/sidemenu/employee/empdetail.html
  semi-project/src/main/resources/templates/sidemenu/employee/employee.html
  semi-project/src/main/resources/templates/sidemenu/employee/logistics.html
  semi-project/src/main/resources/templates/sidemenu/employee/management.html
  semi-project/src/main/resources/templates/sidemenu/employee/marketing.html
  semi-project/src/main/resources/templates/sidemenu/employee/sales.html
  semi-project/src/main/resources/templates/sidemenu/mail/archived.html
  semi-project/src/main/resources/templates/sidemenu/mail/important.html
  semi-project/src/main/resources/templates/sidemenu/mail/mail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailDetail.html
  semi-project/src/main/resources/templates/sidemenu/mail/mailSent.html
  semi-project/src/main/resources/templates/sidemenu/mail/trash.html
  메탈슬러그 각성.lnk
  세븐나이츠 키우기.lnk
Labels: 🖥️프론트엔드🖥️

#257 [24.12.30]구조동물카테고리검색수정,마이페이지전화번호변경수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
  semi-project/src/main/resources/static/sidemenu/mypage/css/calendar-style.css
  semi-project/src/main/resources/templates/sidemenu/adoption/adoptingDetail.html
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
  semi-project/src/main/resources/templates/sidemenu/animals/errorPage.html
  semi-project/src/main/resources/templates/sidemenu/mypage/mypage.html
Labels: 🔙백엔드🔙

#258 [241230] 메신저 css수정, 메신저 사용자목록 선택시 대화방 제목 직급, 부서 추가
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
Labels: 🔙백엔드🔙

#259 [24.12.31] 안읽은 메세지 로직 추가
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/controller/ChatController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dao/ChatMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/dto/ChatDTO.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/messenger/model/service/ChatService.java
  semi-project/src/main/resources/mappers/chatMapper.xml
  semi-project/src/main/resources/static/sidemenu/messenger/css/messenger-style.css
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#264 [24.12.31] 조직도 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/manager/controller/ManagerApprovalController.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/employee/css/employee-style.css
  semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
  semi-project/src/main/resources/static/sidemenu/employee/js/empManagement.js
  semi-project/src/main/resources/templates/sidemenu/employee/employee.html
  semi-project/src/main/resources/templates/sidemenu/employee/management.html
Labels: 🖥️프론트엔드🖥️, 🔙백엔드🔙, ✅PR(Pull Request)✅

#265 [24.12.31] 대표 사번 결재로직 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/approval/controller/ApprovalController.java
  semi-project/src/main/resources/static/img/profile/양파쿵야.png
  메탈슬러그 각성.lnk
  세븐나이츠 키우기.lnk
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅
