Repository 1995-s-Project/1995-s_GroupWare, pull requests merged in 2025-01, with the labels that each got.

#268 [25.01.01] 연차&휴가 관리 CSS 일부 수정
  semi-project/src/main/resources/static/sidemenu/manager/css/vacationManagement.css
Labels: 🖥️프론트엔드🖥️, ✅PR(Pull Request)✅

#267 25.01.01css점검
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/dao/EmployeeMapper.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/model/service/EmployeeService.java
  semi-project/src/main/resources/mappers/empMapper.xml
  semi-project/src/main/resources/static/sidemenu/employee/css/customer.css
  semi-project/src/main/resources/static/sidemenu/employee/css/dog.css
  semi-project/src/main/resources/static/sidemenu/employee/css/employee-style.css
  semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
  semi-project/src/main/resources/static/sidemenu/employee/css/logistics.css
  semi-project/src/main/resources/static/sidemenu/employee/css/marketing.css
  semi-project/src/main/resources/static/sidemenu/employee/css/sales.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailDetail.css
  semi-project/src/main/resources/templates/sidemenu/employee/customer.html
  semi-project/src/main/resources/templates/sidemenu/employee/dog.html
  semi-project/src/main/resources/templates/sidemenu/employee/employee.html
  semi-project/src/main/resources/templates/sidemenu/employee/logistics.html
  semi-project/src/main/resources/templates/sidemenu/employee/management.html
  semi-project/src/main/resources/templates/sidemenu/employee/marketing.html
  semi-project/src/main/resources/templates/sidemenu/employee/sales.html
Labels: 🖥️프론트엔드🖥️

#271 [25.01.01] 웹소켓 로직 일부 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/config/WebSocketConfig.java
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#272 <25.01.02발표전최종수정>
  semi-project/src/main/resources/static/sidemenu/employee/css/empmanagement.css
  semi-project/src/main/resources/templates/sidemenu/board/board.html
  semi-project/src/main/resources/templates/sidemenu/board/search.html
Labels: 🐞버그🐞, 🖥️프론트엔드🖥️

#273 [24.01.02]구조동물 이미지 코드 수정
  semi-project/src/main/java/com/ohgiraffers/semiproject/schedule/controller/ScheduleController.java
  semi-project/src/main/resources/templates/sidemenu/animals/animals.html
Labels: 🔙백엔드🔙

#274 <25.01.02 발표전최종수정3>
  semi-project/src/main/resources/templates/sidemenu/board/title.html
Labels: 🐞버그🐞

#276 [25.01.02] 채팅 로직 수정
  semi-project/src/main/resources/static/sidemenu/messenger/js/messenger.js
  semi-project/src/main/resources/templates/home.html
Labels: 🔙백엔드🔙, ✅PR(Pull Request)✅

#277 <25.01.02발표전최종수정>
  semi-project/src/main/java/com/ohgiraffers/semiproject/board/controller/BoardController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/employee/controller/EmployeeController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/controller/MailController.java
  semi-project/src/main/java/com/ohgiraffers/semiproject/mail/model/service/MailService.java
  semi-project/src/main/resources/templates/sidemenu/board/title.html
Labels: 🛠️수정🛠️

#278 [250102]sout 삭제
  semi-project/src/main/java/com/ohgiraffers/semiproject/animals/controller/AnimalsController.java
Labels: 🔙백엔드🔙

#280 [24.01.02] 페이징처리 수정
  semi-project/src/main/resources/static/sidemenu/mail/css/mail-style.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailArchived.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailImportant.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailSent.css
  semi-project/src/main/resources/static/sidemenu/mail/css/mailTrash.css
  semi-project/src/main/resources/static/sidemenu/manager/css/vacationManagement.css
Labels: 🖥️프론트엔드🖥️, ✅PR(Pull Request)✅
